### ISSUE TITLE
DCO check isn't working

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/cgroups#164]
We should have DCO checking like this: 
https://github.com/containerd/go-cni/blob/0553354f0046ccd41a02e724826040491a3d8998/.travis.yml#L18

**Comment by estesp** [comment]
Looks like adding the matrix entry that does the v2 test via travis+vagrant is somehow skipping the existing "`script:`" section which already had a working DCO check.

I might take a stab at switching this repo over to GH actions since you've done the work to get Vagrant up under GH actions+MacOS instance.
