### ISSUE TITLE
NewSystemd must not ignore UnitExists

### ISSUE THREAD

**Issue by kolyshkin** [containerd/cgroups#279]
This is the same issue as described in https://github.com/opencontainers/runc/issues/3780

In short, `NewSystemd` ignores `UnitExists` error from systemd, as a result the PID is not added to the proper systemd unit and thus the cgroup.

See the above issue for details as to how that may happen.

See the https://github.com/opencontainers/runc/pull/3782 as to how this might be fixed.

**Comment by danishprakash** [comment]
I'll take a look at this

**Comment by mmerkes** [comment]
I assume that [this is the block](https://github.com/containerd/cgroups/blob/fb1932a470d376253001b816abdaff37037284cb/cgroup2/manager.go#L869-L877) that you're talking about refactoring? In a nutshell, are you proposing the following:

1. If you get a unit exists error, reset the systemd unit like [here](https://github.com/kolyshkin/runc/blob/82bc89cd10eb5fa5fdb5d77e41b7ea3c07f9d834/libcontainer/cgroups/systemd/common.go#L200-L207) and try again.
2. If the retry fails, return an error rather than quietly complete.

I'll see if I can throw together a PR. Seems straightforward enough, if my understanding is correct...

**Comment by kolyshkin** [comment]
> I assume that [this is the block](https://github.com/containerd/cgroups/blob/fb1932a470d376253001b816abdaff37037284cb/cgroup2/manager.go#L869-L877) that you're talking about refactoring? In a nutshell, are you proposing the following:
> 
> 1. If you get a unit exists error, reset the systemd unit like [here](https://github.com/kolyshkin/runc/blob/82bc89cd10eb5fa5fdb5d77e41b7ea3c07f9d834/libcontainer/cgroups/systemd/common.go#L200-L207) and try again.
> 2. If the retry fails, return an error rather than quietly complete.
> 
> I'll see if I can throw together a PR. Seems straightforward enough, if my understanding is correct...

@mmerkes yes, your understanding is correct. The most straightforward fix would be to merely return a "unit already exists" error and when fix the callers who do not expect it. The slightly more elaborated one is to call reset-failed (which will remove the failed/non-running unit, if exists) and retry, like I did in runc/libcontainer/cgroups.
